config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "users#index"
  # get "/users" , to: "users#index",  as: "users"
  # get "/users/:id" , to: "users#show" , as: 'user'
  # get "/users/:id/posts" , to: "posts#index", as: "user_posts"
  # get "/users/:id/posts/:id" , to: "posts#show", as: "user_post"
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create] do
      resources :comments, only: [:new, :create]
      resources :likes, only: [:create]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post, class_name: 'Post'

  after_save :update_comment_count

  private

  def update_comment_count
    post.increment!(:comments_counter)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post

  after_save :update_like_count

  private

  def update_like_count
    post.increment!(:likes_counter)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :comments
  has_many :likes

  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, numericality: { greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { greater_than_or_equal_to: 0 }

  after_save :update_posts_count

  def five_most_recent_comments
    comments.order(created_at: :desc).limit(5)
  end

  private

  def update_posts_count
    author.increment!(:postsCounters)
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, foreign_key: 'author_id'
  has_many :comments, foreign_key: 'author_id'
  has_many :likes, foreign_key: 'author_id'

  validates :name, presence: true
  validates :postsCounters, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def three_most_recent_posts
    posts.order(created_at: :desc).limit(3)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :current_user
  def current_user
    @current_user = User.first
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @post = @current_user.posts.find(params[:post_id])
  end

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new(comment_params)
    @comment.author = @current_user
    if @comment.save
      @user = User.find(params[:user_id])
      redirect_to user_post_path(@user, @post)
    else
      render :new
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def new
    @user = User.find(params[:user_id])
  end

  def create
    @user = User.find(params[:user_id])
    @post = Post.find(params[:post_id])
    @like = @post.likes.new
    @like.author = @user
    if @like.save
      redirect_to user_post_path(@user, @post)
    else
      render :new
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = @current_user.posts.new
  end

  def create
    @user = User.find(params[:user_id])
    @post = @user.posts.new(post_params)
    @post.comments_counter = 0
    @post.likes_counter = 0
    respond_to do |format|
      format.html do
        if @post.save
          redirect_to user_posts_path(@user)
        else
          render :new, locals: { post: @post }
        end
      end
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_form.html.erb
<%= form_with model:[@current_user, @post, Comment.new], url:user_post_comments_path(@current_user, @post) do |form| %>

    <div class="comment_form">

      <div>

        <%= form.label :comment%><br>

        <%= form.text_area :text, class:'comment_input' %>
        <% form.object.errors.full_messages_for(:text).each do |message|%>

        <div><%= message %></div>

        <%end%>

      </div>

      <br>

      <%= form.submit class:'post_button' %>

    </div>

<%end%>

app/views/comments/new.html.erb
<%= render "form", post:@post%>
<%= render "form", comment:@comment%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/likes/_form.html.erb
<%= form_with model:[@user, @post, Like.new], url:user_post_likes_path(User.find(params[:user_id]), @post) do |form| %>
    <div class="like_form">
      <%= form.submit "Like", class:'post_button' %>
    </div>
<%end%>

app/views/posts/_form.html.erb
<%# <%= form_with model: [@current_user, @current_user.posts.build] do |form| %> 
<%= form_with model: @current_user, url: user_posts_path, method: post, local: true, scope: :post do |form| %>  
  <div class="post_form">
    <h3> Add New Post </h3>
      <div>
      <%= form.label :title  %><br>
      <%= form.text_field :title, class:'post_title'%>
      <% form.object.errors.full_messages_for(:title).each do |message|%>
      <div><%= message %></div>
      <%end%>
    </div>
      <br>
     <div>
       <%= form.label :text%><br>
        <%= form.text_area :text, class:'post_text'%>
        <% form.object.errors.full_messages_for(:text).each do |message|%>
        <div><%= message %></div>
        <%end%>
     </div>
     <br>
      <%= form.submit "Create Post", class:"post_button"%>
    </div>
<%end%>

app/views/posts/index.html.erb
<h1>list of posts for a given user </h1>
 <div class="post_list">
   <% @posts.each do |post| %>

      <%= render 'shared/post', post:post %>

     <% unless post.five_most_recent_comments.empty?%>
         <div class ="post_comment">
     <%post.five_most_recent_comments.each do |comment| %>
          <%= render 'shared/comment', comment:comment %>
       <% end %>
        </div>
     <% end %>
   <% end %>
  </div>
<div class="button_holder">
<button>Pagination</button>
<button><%= link_to 'Back', :back %></button>
</div>

app/views/posts/new.html.erb
<%= render "form", post:@post%>

app/views/posts/show.html.erb
<h1> Post detail with comments  </h1><h1> Post detail with comments  </h1>
<div class="post_detail">

  <div class="post_detail_card">
  <div class="post_detail_card_header">
   <p class ="post_title_card"> Post # <%=@post.id%> by <%=@post.author.name%></p>
    <p>Comments: <%=@post.comments_counter%> Likes: <%=@post.likes_counter%></p>
  </div>
  <div>
    <p><%=@post.text%></p>
  </div>
    </div>
   <% if !@post.comments.empty?%>
    <div class ="post_detail_comment">
     <% @post.comments.each do |comment| %>
       <%= render 'shared/comment', comment:comment %>
       <% end %>
  </div>
    <%end%>
     <div class="comment_like_holder">

     <div class= "comment_form_holder">
       <h3>Leave a comment</h3>
      <%= render 'comments/form', comment: @comment %>
      </div>

       <div class="like_form_holder">
        <h3>Like this post</h3>
        <%= render 'likes/form', like: @like %>
        </div>
      </div>
</div>

app/views/shared/_comment.html.erb
<p><span>Username:</span><%=comment.author.name %>
<span>Comment:</span><%=comment.text %> </p>

app/views/shared/_post.html.erb
<div class= "post_card">
<h4>
 <%= link_to "Post ##{post.id }", "/users/#{@user.id}/posts/#{post.id}" %>
 </h4>
      <p> <%= post.title %> </p>
      <p class="post_counter"><span>comments: <%=post.comments_counter%> </span>
       <span>Likes: <%=post.likes_counter%> </span>
       </p>
</div>

app/views/shared/_user.html.erb
<div class= "user">
 <div class="user_card">
<div class="user_card_image">
<img class="image-placeholder"src="<%= user.photo %>" alt="add-image"/>
</div>
 <div class="user_card_detail">
<h2><%= link_to user.name, user %></h2>
<p>Number of posts: <%= user.postsCounters %></p>
</div>
</div>
</div>

app/views/users/index.html.erb
<h1>List of users </h1>
<% @users.each do |user| %>
    <%= render 'shared/user', user:user%>
<%end%>

app/views/users/show.html.erb
<h1>A given User detail with posts</h1>
<%= render 'shared/user', user:@user%>

<div class="user_bio">
 <h3>Bio</h3>
 <p><%= @user.bio %><p>
</div>

<div class="user_post">
   <% @user.three_most_recent_posts.each do |post| %>

      <%= render 'shared/post', post:post %>
   <%end%>

</div>
<div class="button_holder">
<button>
<%= link_to 'Create new post', new_user_post_path(@user)%>
</button>
<button>
 <%= link_to 'See all posts', user_posts_path(@user,@posts) %>
</button>
<button>
 <%= link_to 'Back', :back %>
</button>
</div>